### ISSUE TITLE
Deploy rails app on AWS or Linode or equivalent

### ISSUE THREAD

**Issue by AlexB52** [enspiral-dev-academy/coaching#100]

**Comment by AlexB52** [comment]
@donlewi 

I would like a breakout on deploying a rails app on another hosting company than Heroku using deployment tools. The app doesn't matter but it should get tricky features like uploading files for example.  Where do the files go when not on my local machine ?

**Comment by danalexilewis** [comment]
@AlexB52 Hmmm ok. So where you can deploy is dependant on the server running the tech stack you  want to deploy. Eg I could not deploy a rails app to Webbase.co.nz who I use to host a few sites as they only support an AMP stack (Apache, MySql anh PHP).

I use AppHarbour for .net apps and it functions very similarly to heroku. I would say that as long as you are using hosted services like heroku/AppHarbour the process would be very similar with deploying from git.

As for the files question. Do you mean the ruby/rails files? Or the uploaded files?

This sounds like a Q&A on deployments. how does that sound?

**Comment by danalexilewis** [comment]
copied from last ticket:

Alex wrote
I have a lot of trouble about understanding deployment and do not want to see Heroku as magic. 

I would like to know what is minimum required for web deployment. 
What is a dyno in Heroku ? 
What are the basic principles to scale? 
How would a server look like if I have want to get some background jobs, and two instances of my website running ?  

I hear a lot about Chef, Capistrano, Vagrant Nginx, Passenger, Docker. What are they supposed to do ? A brief intro is enough.

Short story, I would like a intro on dev ops. I just do not know how to start.

**Comment by ghost** [comment]
Did a basic breakout on devops. This is a bit broader than that though. I think the rest of Alex's questions around deploying to hosting environments got covered off in the lecture on web performance - which took in server farms and how things get deployed to some extent.

**Comment by AlexB52** [comment]
Yeah it did answer some of my questions !
I still would like, if possible, a live rails deployment breakout to to get a better understanding on how things are done to deploy on a vps. Thanks
