### ISSUE TITLE
javascript framework overview

### ISSUE THREAD

**Issue by joshuavial** [enspiral-dev-academy/coaching#104]
react, backbone, angular, knockout

**Comment by danalexilewis** [comment]
I suppose this is applicable to phase 2 and 3 at this point?

**Comment by joshuavial** [comment]
yes, though I would make it a general overview of each technology and an
open invite for all phases.

On 23 April 2015 at 09:02, Daniel Lewis notifications@github.com wrote:

> I suppose this is applicable to phase 2 and 3 at this point?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/enspiral-dev-academy/coaching/issues/104#issuecomment-95335482
> .

## 

http://enspiral.com/        _Joshua Vial      *
*Phone_ +64 21 684 495
*Skype  *joshuavial *Website *www.enspiral.com
*Twitter  \* @joshuavial http://twitter.com/joshuavial

**Comment by bas-ie** [comment]
I'd be keen.

**Comment by iainkirkpatrick** [comment]
me second!

**Comment by lukekavanagh** [comment]
Me three!

Sent from Yahoo Mail on Android

**Comment by kirstylm** [comment]
Me four :)

**Comment by geordidearns** [comment]
I fifth that if it hasn't already been

**Comment by pietgeursen** [comment]
keenbeanz

**Comment by danalexilewis** [comment]
Wow such interest! this will probably happen later this week.

**Comment by danalexilewis** [comment]
Ok update: This coming week we have 2 seminars on angular and node. the following week is SEO and it is final project week for hihi. So I am planning  to find someone to come and give a seminar the following week. ie 3 weeks from now...

However. This is quite far away so i will run a smaller and shorter breakout on tuesday @ 5 after standup.

**Comment by danalexilewis** [comment]
This will be covered at the tech talk on monday
