### ISSUE TITLE
OOJS Breakout

### ISSUE THREAD

**Issue by geordidearns** [enspiral-dev-academy/coaching#109]
Could i please get a 30-45min breakout on OOJS with a coach sometime this week please. Preferably solo or small group because I seem to learn better that way, Thanks

**Comment by danalexilewis** [comment]
finding a coach

**Comment by danalexilewis** [comment]
amelia will be in thursday

**Comment by kirstylm** [comment]
I would love to sit in if that would be okay.

**Comment by geordidearns** [comment]
no worries @kirstylm, I will be wanting to take it reasonably slow though as i want to really understand the concepts. hence why solo/small group comment above. Amelia has work so will try schedule for sometime after 6pm.

**Comment by kirstylm** [comment]
@geordidearns totally understand, thank you :)
