### ISSUE TITLE
Number in Words Phase1 Walk through

### ISSUE THREAD

**Issue by cjsamodiaz** [enspiral-dev-academy/coaching#111]
Looking for a coach to walk me over this challenge tomorrow Tuesday(5/05/2015) or the following days.

**Comment by danalexilewis** [comment]
we can schedule this in at 5?

**Comment by cjsamodiaz** [comment]
Dan can we re-sched on thursday?

**Comment by danalexilewis** [comment]
sure. say 6.30 tommorrow

**Comment by danalexilewis** [comment]
im closing this. got in touch when your feeling better
