### ISSUE TITLE
P3 angular breakout - Whos keen

### ISSUE THREAD

**Issue by danalexilewis** [enspiral-dev-academy/coaching#112]

**Comment by pietgeursen** [comment]
I'm keen

**Comment by bas-ie** [comment]
I'd be keen to at least sit in, my ng is fairly entry-level ;)

**Comment by HarrietM** [comment]
Keen

**Comment by kirstylm** [comment]
I'd be keen to sit in too :)

**Comment by geordidearns** [comment]
super keen for this!

**Comment by iainkirkpatrick** [comment]
yep if intermediate kids are allowed

**Comment by danalexilewis** [comment]
Update: touching base with Jess in the Alumni community and she looks good to come in next week. Fingers crossed. Will firm up in the next day or two

**Comment by danalexilewis** [comment]
Wendsday 13th @ 6-7

**Comment by JessJK** [comment]
Hey 

If people could give me an idea of what they want to know then I can direct the breakout into specifics or broad overview.

**Comment by geordidearns** [comment]
I wouldn't mind an overview from the beginning to know how it all works. I have basic syntactic exposure. Not sure about everyone else.
