### ISSUE TITLE
Coaching Session Please

### ISSUE THREAD

**Issue by matthewbullock** [enspiral-dev-academy/coaching#116]

**Comment by danalexilewis** [comment]
Hi Matthew - i will see about organising this to happen this week - what specifically do you want to work on.

**Comment by matthewbullock** [comment]
Thankyou!!I never really got around to working on the race car challenge. So I would like to go through that challenge and just get ideas on how you would approach these sort of challenges. Also i would just like some further clarification on creating new instances of objects and properties? Cheers
