### ISSUE TITLE
Would like breakout (?) on ARGV for ruby

### ISSUE THREAD

**Issue by libbyschuknight** [enspiral-dev-academy/coaching#120]
other rubyists in roa may like to join

**Comment by data-doge** [comment]
does after afternoon lecture on monday work? shouldn't take more than 5-10 minutes.

**Comment by libbyschuknight** [comment]
Hey hmmm yeah. Raquel is going to organise a break out on agile for Monday or Tuesday, so the day that that isn't on maybe? 

Thanks 

---

Libby Schumacher-Knight
