### ISSUE TITLE
Break out for self, public/private

### ISSUE THREAD

**Issue by libbyschuknight** [enspiral-dev-academy/coaching#121]
most rubyists keen for break out on self use in classes, public & private interfaces/methods/variables etc

**Comment by data-doge** [comment]
hey joshua, could you do a quick breakout with the phase 1 rubyists tomorrow morning after lecture? I covered 'self' today, and functionally how 'private' works,  but I wasn't entirely clear on the value of public/private methods -- when and why to use them, etc.
