### ISSUE TITLE
personal project - javascript

### ISSUE THREAD

**Issue by OBaddeley** [enspiral-dev-academy/coaching#125]
Long shot but wondering if anyone would be free tomorrow (Sunday) to look at this? Cheers

**Comment by data-doge** [comment]
does another time work for you?

**Comment by OBaddeley** [comment]
Hi, tonight? or Tuesday lunch?

**Comment by data-doge** [comment]
either works, I'm here til 8 tonight, otherwise, 1:00 tomorrow?
