### ISSUE TITLE
Ajax - Useful, or communist plot?

### ISSUE THREAD

**Issue by TomPedersen** [enspiral-dev-academy/coaching#126]
Personal coaching request

**Comment by michael-smith-nz** [comment]
I'm happy to walk you through what it is, when and when not to use Ajax in the real world. Would that help? Or are you wanting a one-on-one coding session?

**Comment by TomPedersen** [comment]
Your offer would be valuable, though a one-on-one coding session would be appreciated as well as it would help more directly with personal shortcomings.
