### ISSUE TITLE
series of small OOJS questions

### ISSUE THREAD

**Issue by iainkirkpatrick** [enspiral-dev-academy/coaching#127]
@peterjacobson and I have come across a few small blocks as we work on a project that we would like some clarification on...
- where to put helper functions / objects? best practice for referencing them (holding them on a model as a property etc?)
- opinions around 'messages' between objects - which object should own the method for communication between two objects? i.e. should the method be on the sender, or the receiver?
- mixins in JS: is this a good idea? (i.e. pieces of code that work like interfaces in C#, can be passed around to be implemented by classes). Or multiple inheritance instead?

any js guru (@ootoovak or @joshuavial?)

**Comment by data-doge** [comment]
what time works for yall?
