### ISSUE TITLE
[Dan] Ajax overview

### ISSUE THREAD

**Issue by danmorrisonNZ** [enspiral-dev-academy/coaching#13]
Would like to learn more about Ajax and how it works with ruby/sinatra

**Comment by joshuavial** [comment]
@danmorrisonNZ @eedrah @tojarra when would you like to do this?

**Comment by eedrah** [comment]
I think this was covered the other day for me. Cheers.

**Comment by joshuavial** [comment]
@danmorrisonNZ I have closed this ticket, let me know if you want to revisit any of it.
