### ISSUE TITLE
Js coaching available :)

### ISSUE THREAD

**Issue by amelialaundy** [enspiral-dev-academy/coaching#137]
Holla if anyone wants to do some javascripty goodness this coming week in the evenings

**Comment by CraigKuriger** [comment]
@amelialaundy If you're going to be in here I could use some JS coaching, anytime would suit : )

**Comment by Jayklutch** [comment]
Aaaaaaaaaaawwwwwwwwwwww

Best regards,
Jay Davis

Solutions Partner,
NZero Ltd
www.nzero.io
Cell: 0224558824

**Comment by juliangommans** [comment]
Is it too late to claim?
