### ISSUE TITLE
[Jesse] Testing MVC in Visual Studio

### ISSUE THREAD

**Issue by eedrah** [enspiral-dev-academy/coaching#19]
Testing MVC in Visual Studio

**Comment by danalexilewis** [comment]
Are you after a p guideline for what to test in an ASP.Net project?

**Comment by danalexilewis** [comment]
@eedrah check this out over the weekend and let me know what you think http://www.pluralsight.com/courses/aspdotnet-mvc-testing-from-scratch

**Comment by eedrah** [comment]
The first half of that was really good - exactly what I was after, cheers.
