### ISSUE TITLE
[Louis] ruby APIS

### ISSUE THREAD

**Issue by Tojarra** [enspiral-dev-academy/coaching#21]
describe "coaching" do 

it *should cover testing" do
 include Ruby, Javascript, JSON 
end

it "should cover 1st submitted personal project" do
include notes on what i missed and what i did wrong
end

end

**Comment by Tojarra** [comment]
have updated ticket to include what still has not been covered.

**Comment by amelialaundy** [comment]
@Tojarra do you want to do this before javascript week or wait until then?

**Comment by Tojarra** [comment]
i hit up samson today to go over first personal project. but testing break out at any point this week would be great.
