### ISSUE TITLE
[Louis] Ajax, DOM manipulation with javascript

### ISSUE THREAD

**Issue by euglazer** [enspiral-dev-academy/coaching#22]

**Comment by danalexilewis** [comment]
has this been booked?

**Comment by Tojarra** [comment]
nope. can we book it?

**Comment by amelialaundy** [comment]
@Tojarra I'll put this back to clarifying, did you want Mikey back in to do it?

**Comment by Tojarra** [comment]
yes please. if possible.

**Comment by ahdinosaur** [comment]
sweet. i'll be at the space tonight for Node.js Hack Night, and i'll see when else i can be around in the near future. unfortunately, my desire to help teach Javascript is much greater than my current capacity to teach, as i'm quite busy with other projects, but i'll see what i can do to help out.
