### ISSUE TITLE
Phill: Going over Ajax and json some time this week

### ISSUE THREAD

**Issue by danalexilewis** [enspiral-dev-academy/coaching#24]

**Comment by rohithyeluri** [comment]
Please include me in this coaching session..  @rohithyeluri

**Comment by Tyesb** [comment]
hey guys are you around tonight for this?

**Comment by rohithyeluri** [comment]
I am fine with today..

**Comment by Tyesb** [comment]
Hey do you guys feel that you still need to have a recap on this or was it covered in your breakout? @donlewi, can you tag Phil in this as well

**Comment by amelialaundy** [comment]
@tyesb all done :)

**Comment by Tyesb** [comment]
Sweet just wanted to clear it off the board :)
