### ISSUE TITLE
Phill - Where is my database?

### ISSUE THREAD

**Issue by rohithyeluri** [enspiral-dev-academy/coaching#27]
I keep loosing the local db that is created by default in Visual Studios - would like a set of clear and consice step to locating the database.

**Comment by rohithyeluri** [comment]
Please include me in this coaching session..  @rohithyeluri

**Comment by rohithyeluri** [comment]
This is weird - Stop stealing my coaching request please Mr. Yeluri!

**Comment by philldellow** [comment]
This is still pretty werid

**Comment by rohithyeluri** [comment]
Trying to regain ownership of only my identity

**Comment by philldellow** [comment]
Ok thanks - i feel better now already!

**Comment by michael-smith-nz** [comment]
I'll be working with Phil(and Rohith?) on this tonight
