### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by philldellow** [enspiral-dev-academy/coaching#29]
Deploying to Azure - was unable to log in using the enspiral password yesterday and so did not walk through this challenge. Since this is now on the backlog I feel like a walk through the challenge will speed my learning of this.

**Comment by michael-smith-nz** [comment]
Phil mentioned that he could not access Azure with the password given
Phil only needs a run through of deploying anything to Azure. I'll be doing this tonight. I need to confirm with Darcy that the Azure account is still working

**Comment by michael-smith-nz** [comment]
Azure account is working. Will show Phil how to deploy to Azure tonight
