### ISSUE TITLE
[geordi] filtering and sorting arrays and hashes

### ISSUE THREAD

**Issue by joshuavial** [enspiral-dev-academy/coaching#30]

**Comment by joshuavial** [comment]
Pete interested too

**Comment by joshuavial** [comment]
evenings preferred

**Comment by amelialaundy** [comment]
@geordidearns do you still want this? and @petedigipulse

**Comment by geordidearns** [comment]
yes please @amelialaundy  - giving me situations to go through using arrays and hashes would be really helpful. perhaps for 30 mins when you have the time? thanks
