### ISSUE TITLE
[Raquel] Review of phase-0 javascript

### ISSUE THREAD

**Issue by raquelxmoss** [enspiral-dev-academy/coaching#34]
With emphasis on JS syntax please

Towards the end of lunch preferred

**Comment by amelialaundy** [comment]
hey @raquelxmoss I'm happy to do this, we can chat tomorrow and organise :)

**Comment by raquelxmoss** [comment]
Hi @amelialaundy is Friday 1:30pm okay? Ira too.

**Comment by amelialaundy** [comment]
yep for sure @raquelxmoss
