### ISSUE TITLE
[dhara] enumerable

### ISSUE THREAD

**Issue by dharapanda123** [enspiral-dev-academy/coaching#37]

**Comment by dharapanda123** [comment]
how and where to use.Importance. anytime of the week after 6 p:m

**Comment by danalexilewis** [comment]
I think understanding what it is and you see it are things you want to know. is this correct? this kind of relates to your other pending ticket

**Comment by danalexilewis** [comment]
following our convirsation we will look to do a break out demo on this

**Comment by danalexilewis** [comment]
@darcythomas
