### ISSUE TITLE
Ira & Pete Classes help

### ISSUE THREAD

**Issue by iraritchiemeek** [enspiral-dev-academy/coaching#44]
Help with challenges similar to hospital_interface and cookies_and_ovens.

preferred time around 6pm

**Comment by iraritchiemeek** [comment]
Passing methods and arrays across classes

**Comment by amelialaundy** [comment]
@iraritchiemeek and @petedigipulse I can do this on wednesday evening at 6ish?

**Comment by amelialaundy** [comment]
@geordidearns

**Comment by iraritchiemeek** [comment]
When should we do this?

**Comment by danalexilewis** [comment]
@iraithiemeek This is 10 days old now. Do you want to do a coaching session this week on classes? or something else?

**Comment by danalexilewis** [comment]
also assigning it to myself as amelia has gone
