### ISSUE TITLE
Help with ActiveRecord

### ISSUE THREAD

**Issue by geordidearns** [enspiral-dev-academy/coaching#50]
Ira, Geordi, Alex

**Comment by geordidearns** [comment]
Emphasise on associations for myself, Geordi

**Comment by danalexilewis** [comment]
did this happen?

**Comment by geordidearns** [comment]
@donlewi nope, although i have a fairly confident grasp on AR now. unsure about the others

**Comment by danalexilewis** [comment]
hmm ok. I am going to move it to done as it is redundant. 

I will chat to ira and alex tomorrow and have them post new tickets if needed
