### ISSUE TITLE
JS intro Overview before phase two

### ISSUE THREAD

**Issue by geordidearns** [enspiral-dev-academy/coaching#52]
Over the weekend of 21st/22nd if possible please. Could also do a weekend but prefer to get through this week and concentrate on the weeks content first.

**Comment by regan-young** [comment]
Hey man, if you're free, I can come in Saturday arvo around 2-4. Where abouts are you up to in the JS?

**Comment by amelialaundy** [comment]
@geordidearns @regan-young can you re-organise this if it still needs doing? its easiest to @ mention the person who you are replying to on here otherwise no one gets notified :)

**Comment by geordidearns** [comment]
@regan-young apologies i didn't re-organise this. I am free from 2pm or all day sunday. no worries if those times don't work for you, it is very late notice.

**Comment by danalexilewis** [comment]
@geordidearns @regan-young did this happen? otherwise lets see about finding someone for monday/tuesday.

**Comment by geordidearns** [comment]
unfortunately not @donlewi, i think a miscommunication prevented it. I'm at dev academy now going through intro stuff, but it would be nice to go through with a coach as it's still very unfamiliar

**Comment by danalexilewis** [comment]
@geordidearns ok we will chat about this tomorrow

**Comment by regan-young** [comment]
Hey @geordidearns, sorry about this. Just going through Github notifications. Lemme know if you need any JavaScript help. I'm free Wednesday night
