### ISSUE TITLE
Databases Databases Databases C# Help MEEEEEE

### ISSUE THREAD

**Issue by astro8891** [enspiral-dev-academy/coaching#53]

**Comment by Tyesb** [comment]
hey mate are you free tonight? Is it entity or SQL stuff you need to clear up?

**Comment by astro8891** [comment]
Hey there, entity stuff.

**Comment by astro8891** [comment]
Free tonight yes

**Comment by Tyesb** [comment]
Say 6-7pm?

**Comment by astro8891** [comment]
Amazing, see you then!

**Comment by Tyesb** [comment]
hey mate do you mind if dhara sits in on this if tonight suits her?

**Comment by astro8891** [comment]
Not at all, ready to roll after standup
