### ISSUE TITLE
How to setup a database in C# entity framework

### ISSUE THREAD

**Issue by nsovdev** [enspiral-dev-academy/coaching#56]
Need to understand code first and empty

**Comment by nsovdev** [comment]
Dhara wants to join as well

**Comment by joshuavial** [comment]
@NotThatSmith @donlewi can one of you sort this today?

**Comment by danalexilewis** [comment]
@josh ill take it - ryan just asked for the same thing

**Comment by danalexilewis** [comment]
breakout went well - any more help will be done via one on one coaching
