### ISSUE TITLE
[geordi] Sinatra GET/POST help

### ISSUE THREAD

**Issue by geordidearns** [enspiral-dev-academy/coaching#57]

**Comment by geordidearns** [comment]
I would like help with the syntax of GET/POST methods, and the general interaction of all the files, knowing what files to place what code in etc.

**Comment by geordidearns** [comment]
also, the html/ruby mash up is strange.

**Comment by danalexilewis** [comment]
hey geord: i know its js week so would you like to do a ruby coaching session on your personal project around this?

**Comment by geordidearns** [comment]
@donlewi yeah that would be great. I had a chat with joshua about this last week and i was ok then, Getting more confident with it although have hit a bit of a block in regards to multiple views etc. Thanks for sorting this.
