### ISSUE TITLE
quick run on c# basic rules

### ISSUE THREAD

**Issue by astro8891** [enspiral-dev-academy/coaching#59]
basic c# code structure.

I want to know the limitation of some codes and how to write them properly.

I'll make a list of codes that I need clarifications on. ta

**Comment by astro8891** [comment]
hey ash here - this isnt me. who posted this ticket?

**Comment by cjsamodiaz** [comment]
So yeah, that was me. 
What happened is, I am logged in on my account on github and when I go to the waffle board link. I am expecting my account is logged in as well. I didn't noticed that its yours  @astro8891, sorry about that.

you said Dan is gonna delete this, I will just make another ticket.

**Comment by astro8891** [comment]
All good mate!
