### ISSUE TITLE
C# Basics Help

### ISSUE THREAD

**Issue by samragriff** [enspiral-dev-academy/coaching#62]
Need some more help with Methods and Classes in c#, Jesse said he may be able to do something on Monday evening with me. Still not sure why i'm so confused!

**Comment by danalexilewis** [comment]
hey sam is this still something you want?
if so what would you like to focus on?

**Comment by samragriff** [comment]
Hey Dan, we didn't do the Roman numerals over the weekend so keen to tackle that one from where we left it  on tuesday

**Comment by danalexilewis** [comment]
ok will see about getting a coach in.

**Comment by samragriff** [comment]
this has been done - thanks dan.
