### ISSUE TITLE
C# Basic code structure Details

### ISSUE THREAD

**Issue by cjsamodiaz** [enspiral-dev-academy/coaching#63]
We can start on my questions about, methods, classes, collection and enumerable.

After we can try to apply my pseudo code on Sudoku challenge. Thanks :)

**Comment by danalexilewis** [comment]
Ok great. Will get in touch with a coach today

**Comment by cjsamodiaz** [comment]
I didn't expect that you can be assigned on the same day Dan and yeah I can't make it to EDA on the past few days. How about today?

**Comment by danalexilewis** [comment]
we will do this in the afternoon
