### ISSUE TITLE
Simple Authentication with Sinatra

### ISSUE THREAD

**Issue by AlexB52** [enspiral-dev-academy/coaching#64]
get a simple authentication working with sinatra and scypt

**Comment by geordidearns** [comment]
I would also like to join this if thats ok

**Comment by AlexB52** [comment]
6.00 o'clock preferably who can help us ? @euglazer @joshuavial @ootoovak

**Comment by geordidearns** [comment]
I have spoken to alex, perhaps Tuesday due to the big tech talk tonight at EDA

**Comment by data-doge** [comment]
scheduled 6 o'clock
