### ISSUE TITLE
How to scrap Websites

### ISSUE THREAD

**Issue by AlexB52** [enspiral-dev-academy/coaching#67]
How to scrap entire websites for some information when no api is avaialble

**Comment by AlexB52** [comment]
@euglazer @joshuavial 
I am wondering how to do that ? Would one of you go through a breakout with me on this one, please ? I will try to find stuff on the internet before the session. I am ok anytime this week. Thanks

**Comment by data-doge** [comment]
scheduled today 3 'o clock

**Comment by AlexB52** [comment]
Good intro to nokogiri. Very simple to use. Thanks Eugene
