### ISSUE TITLE
[Dhara]phase1 recursion/regex

### ISSUE THREAD

**Issue by dharapanda123** [enspiral-dev-academy/coaching#7]
test driven development
Monday-24thfeb 
evening 6-8

**Comment by danalexilewis** [comment]
I combined the other ticket with this one. heres a list of what i ithink you are asking to go over. is it about right?
1. MVC
2. Regex and how to use in c#
3. CSV files and how to use them
4. Recursion

**Comment by danalexilewis** [comment]
as you are staying in phase 1 i will mark this as done and we will generate new requests on monday
