### ISSUE TITLE
[Olivia] C# basics classes and OO

### ISSUE THREAD

**Issue by OBaddeley** [enspiral-dev-academy/coaching#71]
A visual representation of classes and OO theory and working through an example?

**Comment by danalexilewis** [comment]
@OliviaHihi there will be a breakout on this at 4.20 after thi list one. 10 min + Q&A

**Comment by OBaddeley** [comment]
Have had a breakout with Michael, would still like further work on OO theory and example.

**Comment by michael-smith-nz** [comment]
Scheduled with Olivia either Friday nigth or Monday lunch
