### ISSUE TITLE
Jquery Behavior Drill Solutions

### ISSUE THREAD

**Issue by AlexB52** [enspiral-dev-academy/coaching#76]
I have been stuck and did not manage to solve those exercises. I really would like to see solutions for the week 5 Wednesday morning exercises.

**Comment by AlexB52** [comment]
Just some very simple solution to see the logic. Do not need a complete breakout on them.

**Comment by nsovdev** [comment]
I would like to see the solutions too

**Comment by danalexilewis** [comment]
I will see who has capacity for this this afternoon

**Comment by donlewi** [comment]
requested solution for this week
