### ISSUE TITLE
what is C#?

### ISSUE THREAD

**Issue by amelialaundy** [enspiral-dev-academy/coaching#79]

**Comment by danalexilewis** [comment]
underlying language of the universe - with types to make it all make sense??

**Comment by data-doge** [comment]
wololo

**Comment by danalexilewis** [comment]
longest ticket ever. note i have assigned the ticket to you @amelialaundy so whenever your feeling up to it you can run the seminar for yourself ;) plus anyone else who feels like attending.

**Comment by eedrah** [comment]
I'll take this one - it's a musical note lying a chromatic semitone above C and a diatonic semitone below D. It's around about 277.18 Hz. You  can here it by pasting this into PowerShell: [console]::beep(277.18, 1000)

**Comment by amelialaundy** [comment]
ha mean love the note!

**Comment by amelialaundy** [comment]
I think I figured it out
