### ISSUE TITLE
2nd and 3rd personal project help

### ISSUE THREAD

**Issue by nsovdev** [enspiral-dev-academy/coaching#82]
I will need some help completing the projects.

**Comment by danalexilewis** [comment]
someone on weds

**Comment by donlewi** [comment]
I will do this with you at 6

**Comment by donlewi** [comment]
tomorrow

**Comment by donlewi** [comment]
@regan-young keen to do this tomorrow?

**Comment by danalexilewis** [comment]
mitch will be in at 6 to jam on this with you
