### ISSUE TITLE
Phase Two (week 4 & 5) Tech check-in [geordi]

### ISSUE THREAD

**Issue by geordidearns** [enspiral-dev-academy/coaching#84]
I would like to sit down with a coach for an hour or so and review the topics covered so far to see where my weaknesses are. Anytime in the morning before 8.45am, through-out lunch, or after 6pm any day. Thanks

**Comment by danalexilewis** [comment]
will find out if josh or samson can do this tomorrow
@joshuavial + @ootoovak

**Comment by geordidearns** [comment]
Thanks dan
