### ISSUE TITLE
[P2 BreakOut] ActiveRecord many to many. Accessing through through table

### ISSUE THREAD

**Issue by danalexilewis** [enspiral-dev-academy/coaching#93]

**Comment by danalexilewis** [comment]
@joshuavial  @ootoovak can one of you do this today or tomorrow?

**Comment by ootoovak** [comment]
I am on Axos all day tomorrow. Hopefully @joshuavial or @euglazer can take it?

**Comment by joshuavial** [comment]
Yep, I can do this morning

**Comment by joshuavial** [comment]
https://www.youtube.com/watch?v=PD0-efs7s_A
