### ISSUE TITLE
(Craig) Ruby Algorithms + Recursion

### ISSUE THREAD

**Issue by CraigKuriger** [enspiral-dev-academy/coaching#94]
I could use some extra help with algorithms.

**Comment by stevenb-nz** [comment]
I'd be happy to try helping with this.
- after about 6pm today (Wed 15/4), or
- after about 4.30pm tomorrow.

**Comment by danalexilewis** [comment]
@stevenb-nz thats awesome that your offering to help! I will checkin with craig and see where he is at. I know its last minute and a friday so maybe we will line something up for next week.

**Comment by stevenb-nz** [comment]
Yep, not in Wellington today. Can do 6pm-ish Mon-Thu next week, and should be there all day Fri next week.

**Comment by danalexilewis** [comment]
@CraigKuriger I was chatting to you quick yesterday. Steve would be a great person to have a 1 on 1 session with. Lets line this up for monday.

**Comment by stevenb-nz** [comment]
Okay - will get there for end-of-day standup on Monday, and do this after that.

**Comment by CraigKuriger** [comment]
Yip ,that should be great thanks.

**Comment by CraigKuriger** [comment]
@stevenb-nz thanks for that, any help tonight would be great since I hear algorithms is your forte!

PS, Sorry about my late reply, I got bit behind with github emails.
