### ISSUE TITLE
[Ash] Ajax Session

### ISSUE THREAD

**Issue by astro8891** [enspiral-dev-academy/coaching#96]
Going over the Ajax PP2 challenge
@javascript

**Comment by danalexilewis** [comment]
Hey Ash. Not sure what you mean by Ajax Session - can you clarify?

**Comment by astro8891** [comment]
Personal Project 2 - from start to finish.

**Comment by danalexilewis** [comment]
ahhh ok - hmmmm do you mean like an example of someone solving it?

**Comment by astro8891** [comment]
Going over it with a coach, I didn't finish it and would love the refresher

**Comment by danalexilewis** [comment]
ok - i so like a review of what you have done? and then a chat about what you havent?

**Comment by danalexilewis** [comment]
Hey ill jam on this with you this evening at about 6.30
