### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by AlexB52** [enspiral-dev-academy/coaching#98]

**Comment by AlexB52** [comment]
@donlewi : I hear a lot about API and the fact that our keys need to be part of the environment for me security. How do you create them in a rails app and how do you access them when needed. Thanks

**Comment by danalexilewis** [comment]
roger that, so we can title it: Rails Apis, how to create, issue and track an Api key?

**Comment by data-doge** [comment]
scheduled tentatively for sometime today

**Comment by danalexilewis** [comment]
@euglazer done?
