### ISSUE TITLE
Server architecture

### ISSUE THREAD

**Issue by AlexB52** [enspiral-dev-academy/coaching#99]
@donlewi 

I have a lot of trouble about understanding deployment and do not want to see Heroku as magic. 

I would like to know what is minimum required for web deployment. 
What is a dyno in Heroku ? 
What are the basic principles to scale? 
How would a server look like if I have want to get some background jobs, and two instances of my website running ?  

I hear a lot about Chef, Capistrano, Vagrant Nginx, Passenger, Docker. What are they supposed to do ? A brief intro is enough.

Short story, I would like a intro on dev ops. I just do not know how to start.

**Comment by danalexilewis** [comment]
Sweet i see this very much like the second ticket you posted. Lets bundle them together and call it a intro/Q&A on DevOps
